
server.port=8080

server.error.whitelabel.enabled = true

# Giving a root path to the app
#server.servlet.context-path = /empwebapp
#spring.application.name = /empwebapp

logging.file.name = src/main/resources/scripts/applogs/app.log
logging.file.clean-history-on-start = true

#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=hr_dev_db;encrypt=true;trustServerCertificate=true
#L'Explorateur d'objets montre clairement que votre base de données hr_dev_db se trouve sur l'instance DESKTOP-OMKJ3S1\SQLEXPRESS.Actuellement, votre fichier application.properties de Spring Boot tente de se connecter à localhost:1433. Par défaut, le port 1433 redirige vers l'autre instance
spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=hr_dev_db1;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=create-drop


# Some properties *****************************************************************************************************************
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp
logging.level.org.springframework.web=debug
logging.level.org.springframework.boot.autoconfigure.data.rest = debug
logging.level.org.springframework.boot.autoconfigure.data.jpa = debug
logging.level.org.springframework.boot.autoconfigure.orm = debug
logging.level.org.springframework.data = debug
logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen RDBMS
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update
# Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.ddl-auto = update

# Show or not log for each sql query ***********************************************************************************************
spring.jpa.show-sql = true
#spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.*=true
#spring.jpa.properties.hibernate.enable_lazy_load_no_trans = true


#spring.jpa.properties.javax.persistence.schema-generation.create-source = metadata
#spring.jpa.properties.javax.persistence.schema-generation.scripts.action = create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target = src/main/resources/scripts/SQL/hr_schema_db.sql


